spring:
   application:
    name: JPA with Database
   datasource:
    url: jdbc:postgresql://localhost:5432/mylocal?currentSchema=shaileshtest
    password: postgres
    username: postgres
    driver-class-name: org.postgresql.Driver
   http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
      force-request: true
      force-response: true
   jpa:
    show-sql: "true"
    properties:
      hibernate.format_sql: "true"
    hibernate:
      ddl-auto: update
      
   jackson:
    serialization:
      write-dates-as-timestamps: false
 